all: problem1 problem2 problem3 problem4

CC = g++
CFLAGS = -O2 -openmp

problem1: problem1.cpp
	$(CC) $(CFLAGS) -o problem1 $<

problem2: problem2.cpp
	$(CC) $(CFLAGS) -o problem2 $<

problem3: problem3.cpp
	$(CC) $(CFLAGS) -o problem3 $<

problem4: problem4.cpp
	$(CC) $(CFLAGS) -o problem4 $<

clean:
	rm -f problem1
